services:
  collector:
    image: otel/opentelemetry-collector:latest
    container_name: collector
    hostname: collector
    depends_on:
      - tempo
    command: ["--config=/etc/collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/collector-config.yaml
    ports:
      # Default gRPC port
      - "4317:4317"
      # Default HTTP port
      - "4318:4318"

  grafana:
    image: grafana/grafana:latest
    ports:
      - 5000:3000
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
